# Generated by Django 5.0.1 on 2024-01-08 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price_per_unit',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_ingredient', to='recipeapp.ingredient'),
        ),
    ]
