# Generated by Django 5.0.1 on 2024-01-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_rename_brand_grocerystoreitem_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerystoreitem',
            name='storage_type',
            field=models.CharField(blank=True, choices=[('R', 'Refrigerator'), ('P', 'Pantry'), ('F', 'Freezer')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='grocerystoreitem',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand name'),
        ),
        migrations.DeleteModel(
            name='StorageType',
        ),
    ]
