# Generated by Django 5.0.1 on 2024-01-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_alter_ingredient_price_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='substitute',
        ),
        migrations.DeleteModel(
            name='Substitute',
        ),
    ]
