# Generated by Django 5.0.1 on 2024-01-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_remove_ingredient_substitute_delete_substitute'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrivalues',
            name='ing_name',
            field=models.CharField(default='None', max_length=100, verbose_name='Ingredient name'),
        ),
    ]
