# Generated by Django 5.0.1 on 2024-01-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_alter_grocerystoreitem_storage_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='storage_type_category',
        ),
        migrations.AddField(
            model_name='category',
            name='grocery_item_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
    ]
