# Generated by Django 5.0.1 on 2024-01-08 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0004_nutrivalues_ing_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipe',
            new_name='recipe_ing',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeapp.recipeingredient'),
        ),
        migrations.AlterField(
            model_name='nutrivalues',
            name='ing_name',
            field=models.CharField(default='None', max_length=100, verbose_name='Name'),
        ),
    ]
