# Generated by Django 5.0.1 on 2024-01-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0004_remove_category_storage_type_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerystoreitem',
            name='store_item_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item name'),
        ),
    ]
