# Generated by Django 5.0.1 on 2024-01-13 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0005_grocerystoreitem_store_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='grocery_store_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeapp.grocerystoreitem'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeapp.ingredientmeasurement'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
