# Generated by Django 5.0 on 2024-01-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0005_rename_recipe_recipeingredient_recipe_ing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='measurementtype',
            options={'verbose_name': 'Measurement type', 'verbose_name_plural': 'Measurement types'},
        ),
        migrations.AlterModelOptions(
            name='nutrivalues',
            options={'verbose_name': 'Nutrient value', 'verbose_name_plural': 'Nutrient values'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Recipe ingredient', 'verbose_name_plural': 'Recipe ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipeinstruction',
            options={'verbose_name': 'Recipe instruction', 'verbose_name_plural': 'Recipe instructions'},
        ),
        migrations.AlterModelOptions(
            name='storagetype',
            options={'verbose_name': 'Storage type', 'verbose_name_plural': 'Storage types'},
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipe_ing',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_ingredients',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
    ]
