# Generated by Django 5.0.1 on 2024-01-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0006_alter_category_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinstruction',
            name='instruction',
            field=models.TextField(max_length=1000, verbose_name='Instruction'),
        ),
    ]
