# Generated by Django 5.0.1 on 2024-01-13 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0008_remove_grocerystoreitem_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='grocery_store_item',
        ),
        migrations.AddField(
            model_name='grocerystoreitem',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeapp.brand'),
        ),
    ]
