# Generated by Django 5.0.1 on 2024-01-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0009_nutrivalues_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrivalues',
            options={'verbose_name': 'Nutritional value', 'verbose_name_plural': 'Nutritional values'},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='nutritional_value',
        ),
    ]
