# Generated by Django 5.0.1 on 2024-01-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0010_alter_nutrivalues_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeapp.category'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='net_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Net weight (g/ml)'),
        ),
    ]
