# Generated by Django 5.0.1 on 2024-01-12 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0010_alter_nutrivalues_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeapp.category'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='net_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Net weight (g/ml)'),
        ),
        migrations.CreateModel(
            name='IngredientVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand')),
                ('net_weight', models.FloatField(blank=True, null=True, verbose_name='Net weight (g/ml)')),
                ('price_per_unit', models.FloatField(verbose_name='Price')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeapp.category')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeapp.ingredient')),
                ('storage_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeapp.storagetype')),
            ],
        ),
    ]
