# Generated by Django 5.0.1 on 2024-01-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0010_alter_recipe_cuisine_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_desc',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Recipe description'),
        ),
    ]
