# Generated by Django 5.0.1 on 2024-01-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0011_alter_ingredient_brand_alter_ingredient_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientvariant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ingredientvariant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ingredientvariant',
            name='storage_type',
        ),
    ]
