# Generated by Django 5.0.1 on 2024-01-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0012_remove_ingredientvariant_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand')),
                ('net_weight', models.FloatField(blank=True, null=True, verbose_name='Net weight (g/ml)')),
                ('price_per_unit', models.FloatField(verbose_name='Price')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='storage_type',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='nutrivalues',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='nutrivalues',
            name='brand_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeapp.brandingredient'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='brand_ingredients',
            field=models.ManyToManyField(to='recipeapp.brandingredient'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeapp.category')),
                ('storage_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeapp.storagetype')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.AddField(
            model_name='brandingredient',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipeapp.product'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeapp.product'),
        ),
        migrations.DeleteModel(
            name='IngredientVariant',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
